name: challenge_liber_quiz

description: "Aplicación de cuestionarios para entrevistas técnicas usando Flutter y BLoC"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  uuid: ^4.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^9.1.4

flutter:
  uses-material-design: true
